services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test-pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
